## Imports & Setup

In [1]:
import pandas as pd
import numpy as np

from datetime import datetime, timedelta
from os.path import exists as pexists
from os.path import join as pjoin

from matplotlib import pyplot as plt
from matplotlib import dates as mdates
from matplotlib import patches as mpatches
from matplotlib.lines import Line2D
from matplotlib.patches import Patch
from solo_epd_loader import epd_load

dir_inputs = "inputs"
dir_data = "data"
dir_saves = "intermediate_states"
dir_plots = "plots"

WARNING: SunpyUserWarning: Importing sunpy.timeseries without its extra dependencies may result in errors.
The following packages are not installed:
['h5py>=3.9.0']
To install sunpy with these dependencies use `pip install sunpy[timeseries]` or `pip install sunpy[all]` for all extras.
If you installed sunpy via conda, please report this to the community channel: https://matrix.to/#/#sunpy:openastronomy.org [sunpy.util.sysinfo]

## Data Read

In [2]:
shocktimes = pd.read_csv(pjoin(dir_inputs, "shocks.dat"),
                               sep=";",
                               header=None,
                               skiprows=24,
                               usecols=[0, 1, 2, 3, 4, 5])
shocktimes["Datetime"] = [datetime(row[0], row[1], row[2], row[3], row[4], row[5]) for _, row in shocktimes.iterrows()]
for i in range(6):
    del shocktimes[i]
shocktimes = pd.Series(shocktimes["Datetime"])
display(shocktimes.info())
shocktimes

<class 'pandas.core.series.Series'>
RangeIndex: 70 entries, 0 to 69
Series name: Datetime
Non-Null Count  Dtype
--------------  -----
70 non-null     datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 692.0 bytes

None

0    2021-06-13 10:08:41
1    2021-07-18 17:57:52
2    2021-07-19 08:27:59
3    2021-07-31 00:39:36
4    2021-09-25 18:26:08
             ...
65   2023-11-30 10:47:27
66   2023-12-01 02:26:39
67   2023-12-10 21:14:30
68   2023-12-27 22:22:21
69   2023-12-29 02:28:11
Name: Datetime, Length: 70, dtype: datetime64[ns]

In [3]:
df_event_times = pd.read_excel(pjoin(dir_inputs, "example.xlsx"),
                               header=0,
                               index_col=0,
                               dtype={"Onset Time": "datetime64[ns]"})
df_event_times = df_event_times.dropna(how="all")
for i, row in df_event_times.iterrows():
    if pd.isna(row["BG Start"]):
        df_event_times.at[i, "BG Start"] = row["Onset Time"] - timedelta(hours=2)
    if pd.isna(row["BG End"]):
        df_event_times.at[i, "BG End"] = row["Onset Time"] - timedelta(minutes=5)
    df_event_times.at[i, "End Time"] = row["Onset Time"] + timedelta(hours=24*2)
    for shocktime in shocktimes:
        if df_event_times.at[i, "BG End"] < shocktime < df_event_times.at[i, "End Time"]:
            print(f"Event ({i})", "Replaced", df_event_times.at[i, "End Time"].strftime("%Y-%m-%d %H:%M:%S"), "with shock time", shocktime.strftime("%Y-%m-%d %H:%M:%S"))
            df_event_times.at[i, "End Time"] = shocktime
            break
display(df_event_times.info())
df_event_times

<class 'pandas.core.frame.DataFrame'>
Index: 1 entries, 20 to 20
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Onset Time  1 non-null      datetime64[ns]
 1   BG Start    1 non-null      datetime64[ns]
 2   BG End      1 non-null      datetime64[ns]
 3   End Time    1 non-null      datetime64[ns]
dtypes: datetime64[ns](4)
memory usage: 148.0 bytes

None

,Onset Time,BG Start,BG End,End Time
Event No,,,,
20,2021-11-01 02:05:00,2021-10-31 19:00:00,2021-11-01 01:30:00,2021-11-03 02:05:00

In [4]:
# Data download parameters
plot_buffer_time = timedelta(hours=2)
sensor = "HET"
level = "l2"
viewings = ["sun", "asun", "north", "south"]
data_path = "data"

# Data handling parameters
resample_freqs = [
    timedelta(minutes=2),
    timedelta(minutes=5),
    timedelta(minutes=10),
    timedelta(minutes=30)
]

group_options = {
    "protons": {
        "8 MeV": [1, 2, 3],
        # "10 MeV": [4, 5, 6],
        "25 MeV": [18, 19],
        "50 MeV": [27]
    },
    "electrons": {
        "1 MeV": [0, 1]
    }
}

particle_prefix = {
    "protons": "H",
    "electrons": "Electron"
}

particles = list(particle_prefix.keys())

In [5]:
_, _, energies = epd_load(sensor=sensor,
                          level=level,
                          startdate=df_event_times.iloc[0]["Onset Time"] - plot_buffer_time,
                          enddate=df_event_times.iloc[0]["End Time"],
                          viewing=viewings[0],
                          path=data_path,
                          autodownload=True)
energies

{'H_Bins_Text': array(['7.0450 - 7.3540 MeV', '7.3540 - 7.8900 MeV',
        '7.8900 - 8.4840 MeV', '8.4840 - 9.1840 MeV',
        '9.1840 - 9.6410 MeV', '10.6000 - 10.7400 MeV',
        '10.7400 - 10.9800 MeV', '10.9800 - 11.3500 MeV',
        '11.3500 - 11.8000 MeV', '11.8000 - 12.4300 MeV',
        '12.4300 - 13.6800 MeV', '13.6800 - 14.6100 MeV',
        '14.6100 - 15.6500 MeV', '15.6500 - 16.8200 MeV',
        '16.8200 - 18.2000 MeV', '18.2000 - 19.6500 MeV',
        '19.6500 - 21.2400 MeV', '21.2400 - 23.1200 MeV',
        '23.1200 - 25.0900 MeV', '25.0900 - 27.2000 MeV',
        '27.2000 - 29.4400 MeV', '29.4400 - 31.9700 MeV',
        '31.9700 - 34.8800 MeV', '34.8800 - 37.9000 MeV',
        '37.9000 - 41.1800 MeV', '41.1800 - 44.9900 MeV',
        '44.9900 - 49.0700 MeV', '49.0700 - 53.3800 MeV',
        '53.3800 - 58.0300 MeV', '58.0300 - 63.1000 MeV',
        '63.1000 - 68.9700 MeV', '68.9700 - 75.1100 MeV',
        '75.1100 - 81.6400 MeV', '81.6400 - 89.4600 MeV',
        '89.4600 - 97.6300 MeV', '97.6300 - 104.9000 MeV'], dtype='<U22'),
 'H_Bins_Low_Energy': array([ 7.045,  7.354,  7.89 ,  8.484,  9.184, 10.6  , 10.74 , 10.98 ,
        11.35 , 11.8  , 12.43 , 13.68 , 14.61 , 15.65 , 16.82 , 18.2  ,
        19.65 , 21.24 , 23.12 , 25.09 , 27.2  , 29.44 , 31.97 , 34.88 ,
        37.9  , 41.18 , 44.99 , 49.07 , 53.38 , 58.03 , 63.1  , 68.97 ,
        75.11 , 81.64 , 89.46 , 97.63 ], dtype=float32),
 'H_Bins_Width': array([0.309, 0.536, 0.594, 0.7  , 0.457, 0.14 , 0.24 , 0.37 , 0.45 ,
        0.63 , 1.25 , 0.93 , 1.04 , 1.17 , 1.38 , 1.45 , 1.59 , 1.88 ,
        1.97 , 2.11 , 2.24 , 2.53 , 2.91 , 3.02 , 3.28 , 3.81 , 4.08 ,
        4.31 , 4.65 , 5.07 , 5.87 , 6.14 , 6.53 , 7.82 , 8.17 , 7.27 ],
       dtype=float32),
 'Electron_Bins_Text': array(['0.4533 - 1.0380 MeV', '1.0530 - 2.4010 MeV',
        '2.4010 - 5.9930 MeV', '5.9930 - 18.8300 MeV'], dtype='<U20'),
 'Electron_Bins_Low_Energy': array([0.4533, 1.053 , 2.401 , 5.993 ], dtype=float32),
 'Electron_Bins_Width': array([ 0.5847,  1.348 ,  3.592 , 12.837 ], dtype=float32)}

if data are already downloaded, skip the "download data" cell and run the "load data" cell directly.

In [6]:
# download data
pv = {}
ev = {}
for viewing in viewings:
    if pexists(pjoin(dir_saves, f"protons_{viewing}.pkl")) and pexists(pjoin(dir_saves, f"electrons_{viewing}.pkl")):
        continue
    list_protons = []
    list_electrons = []
    print(viewing, end="...\n")
    for i, row in df_event_times.iterrows():
        print(f"Loading data for {i}...")
        plot_startdate = row["BG Start"] - plot_buffer_time
        plot_enddate = row["End Time"] + plot_buffer_time
        df_protons_event, df_electrons_event, energies = epd_load(sensor=sensor,
                                                                  level=level,
                                                                  startdate=plot_startdate,
                                                                  enddate=plot_enddate,
                                                                  viewing=viewing,
                                                                  path=data_path,
                                                                  autodownload=True)
        list_protons.append(df_protons_event.loc[plot_startdate:plot_enddate])
        list_electrons.append(df_electrons_event.loc[plot_startdate:plot_enddate])
    print(f"{viewing} data loaded.")
    pv[viewing] = pd.concat({i: pe["H_Flux"] for i, pe in zip(df_event_times.index, list_protons)}, axis="index")
    ev[viewing] = pd.concat({i: ee["Electron_Flux"] for i, ee in zip(df_event_times.index, list_electrons)}, axis="index")
    pv[viewing].to_pickle(pjoin(dir_saves, f"protons_{viewing}.pkl"))
    ev[viewing].to_pickle(pjoin(dir_saves, f"electrons_{viewing}.pkl"))
for viewing in viewings:
    if viewing not in pv or viewing not in ev:
        print(f"Loading existing {viewing} data...")
        if not pexists(pjoin(dir_saves, "data_protons.pkl")):
            pv[viewing] = pd.read_pickle(pjoin(dir_saves, f"protons_{viewing}.pkl"))
        if not pexists(pjoin(dir_saves, "data_electrons.pkl")):
            ev[viewing] = pd.read_pickle(pjoin(dir_saves, f"electrons_{viewing}.pkl"))
print("Creating Dataframes...")
if pexists(pjoin(dir_saves, "data_protons.pkl")):
    df_protons = pd.read_pickle(pjoin(dir_saves, "data_protons.pkl"))
else:
    df_protons = pd.concat(pv, axis="columns")
    df_protons.to_pickle(pjoin(dir_saves, "data_protons.pkl"))
    del pv
print("Protons done")
if pexists(pjoin(dir_saves, "data_electrons.pkl")):
    df_electrons = pd.read_pickle(pjoin(dir_saves, "data_electrons.pkl"))
else:
    df_electrons = pd.concat(ev, axis="columns")
    df_electrons.to_pickle(pjoin(dir_saves, "data_electrons.pkl"))
    del ev
print("Electrons done")
print("Done")

sun...
Loading data for 20...
sun data loaded.
asun...
Loading data for 20...
asun data loaded.
north...
Loading data for 20...
north data loaded.
south...
Loading data for 20...
south data loaded.
Creating Dataframes...
Protons done
Electrons done
Done

In [7]:
# load data
particles_dfs = {
    "protons": pd.read_pickle(pjoin(dir_saves, "data_protons.pkl")),
    "electrons": pd.read_pickle(pjoin(dir_saves, "data_electrons.pkl"))
}

In [8]:
for particle in particles:
    wanted_columns = [f"{particle_prefix[particle]}_Flux_{j}"
                        for j in [i for sublist in list(group_options[particle].values())
                                    for i in sublist]]
    for viewing in viewings:
        unwanted_columns = [(viewing, column) for column in particles_dfs[particle][viewing].columns if column not in wanted_columns]
        particles_dfs[particle].drop(columns=unwanted_columns, inplace=True)

In [9]:
particles_dfs["protons"] = particles_dfs["protons"].sort_index(axis="index", level=list(range(particles_dfs["protons"].index.nlevels)))
particles_dfs["electrons"] = particles_dfs["electrons"].sort_index(axis="index", level=list(range(particles_dfs["electrons"].index.nlevels)))
display(particles_dfs["protons"])
display(particles_dfs["electrons"])

                                       sun                                \
                                  H_Flux_1  H_Flux_2  H_Flux_3 H_Flux_18
   Time
20 2021-10-31 17:00:03.197107584  7.345163  2.610080  0.000000  0.000000
   2021-10-31 17:00:08.197116032  0.000000  1.305040  0.000000  0.371879
   2021-10-31 17:00:13.197124608  1.469033  0.000000  0.000000  0.000000
   2021-10-31 17:00:18.197133056  0.000000  1.305040  0.000000  0.000000
   2021-10-31 17:00:23.197141504  0.000000  0.000000  0.000000  0.000000
...                                    ...       ...       ...       ...
   2021-11-03 04:04:38.557996672  2.938066  0.000000  0.000000  0.000000
   2021-11-03 04:04:43.558005120  0.000000  3.915121  1.124859  0.000000
   2021-11-03 04:04:48.558013568  2.938066  2.610080  1.124859  0.000000
   2021-11-03 04:04:53.558022144  4.407098  3.915121  1.124859  0.000000
   2021-11-03 04:04:58.558030592  0.000000  2.610080  0.000000  0.000000

                                                          asun           \
                                 H_Flux_19 H_Flux_27  H_Flux_1 H_Flux_2
   Time
20 2021-10-31 17:00:03.197107584  0.000000       0.0  2.938066  1.30504
   2021-10-31 17:00:08.197116032  0.000000       0.0  0.000000  0.00000
   2021-10-31 17:00:13.197124608  0.000000       0.0  0.000000  0.00000
   2021-10-31 17:00:18.197133056  0.000000       0.0  0.000000  1.30504
   2021-10-31 17:00:23.197141504  0.000000       0.0  0.000000  0.00000
...                                    ...       ...       ...      ...
   2021-11-03 04:04:38.557996672  0.000000       0.0  0.000000  1.30504
   2021-11-03 04:04:43.558005120  0.000000       0.0  2.938066  2.61008
   2021-11-03 04:04:48.558013568  0.000000       0.0  0.000000  1.30504
   2021-11-03 04:04:53.558022144  0.000000       0.0  0.000000  0.00000
   2021-11-03 04:04:58.558030592  0.351062       0.0  1.469033  0.00000

                                                      ...     north            \
                                  H_Flux_3 H_Flux_18  ...  H_Flux_3 H_Flux_18
   Time                                               ...
20 2021-10-31 17:00:03.197107584  0.000000  0.000000  ...  0.000000       0.0
   2021-10-31 17:00:08.197116032  0.000000  0.000000  ...  0.000000       0.0
   2021-10-31 17:00:13.197124608  1.124859  0.000000  ...  1.124859       0.0
   2021-10-31 17:00:18.197133056  1.124859  0.000000  ...  0.000000       0.0
   2021-10-31 17:00:23.197141504  2.249719  0.000000  ...  0.000000       0.0
...                                    ...       ...  ...       ...       ...
   2021-11-03 04:04:38.557996672  1.124859  0.000000  ...  2.249719       0.0
   2021-11-03 04:04:43.558005120  1.124859  0.000000  ...  0.000000       0.0
   2021-11-03 04:04:48.558013568  0.000000  0.371879  ...  2.249719       0.0
   2021-11-03 04:04:53.558022144  0.000000  0.000000  ...  0.000000       0.0
   2021-11-03 04:04:58.558030592  1.124859  0.000000  ...  2.249719       0.0

                                                         south           \
                                 H_Flux_19 H_Flux_27  H_Flux_1 H_Flux_2
   Time
20 2021-10-31 17:00:03.197107584  0.000000       0.0  0.000000  1.30504
   2021-10-31 17:00:08.197116032  0.000000       0.0  0.000000  0.00000
   2021-10-31 17:00:13.197124608  0.000000       0.0  1.469033  1.30504
   2021-10-31 17:00:18.197133056  0.000000       0.0  1.469033  0.00000
   2021-10-31 17:00:23.197141504  0.351062       0.0  2.938066  0.00000
...                                    ...       ...       ...      ...
   2021-11-03 04:04:38.557996672  0.000000       0.0  0.000000  1.30504
   2021-11-03 04:04:43.558005120  0.000000       0.0  1.469033  1.30504
   2021-11-03 04:04:48.558013568  0.000000       0.0  0.000000  1.30504
   2021-11-03 04:04:53.558022144  0.000000       0.0  2.938066  0.00000
   2021-11-03 04:04:58.558030592  0.000000       0.0  1.469033  2.61008


                                  H_Flux_3 H_Flux_18 H_Flux_19 H_Flux_27
   Time
20 2021-10-31 17:00:03.197107584  0.000000  0.000000  0.000000       0.0
   2021-10-31 17:00:08.197116032  1.124859  0.371879  0.351062       0.0
   2021-10-31 17:00:13.197124608  0.000000  0.371879  0.000000       0.0
   2021-10-31 17:00:18.197133056  2.249719  0.000000  0.000000       0.0
   2021-10-31 17:00:23.197141504  1.124859  0.371879  0.000000       0.0
...                                    ...       ...       ...       ...
   2021-11-03 04:04:38.557996672  1.124859  0.000000  0.000000       0.0
   2021-11-03 04:04:43.558005120  2.249719  0.000000  0.000000       0.0
   2021-11-03 04:04:48.558013568  0.000000  0.000000  0.000000       0.0
   2021-11-03 04:04:53.558022144  0.000000  0.000000  0.000000       0.0
   2021-11-03 04:04:58.558030592  0.000000  0.000000  0.000000       0.0

[42540 rows x 24 columns]

                                             sun                  \
                                 Electron_Flux_0 Electron_Flux_1
   Time
20 2021-10-31 17:00:00.197105920       20.680517         0.00000
   2021-10-31 17:00:01.197107584        0.000000         0.00000
   2021-10-31 17:00:02.197109376       20.680517         0.00000
   2021-10-31 17:00:03.197111040        0.000000         0.00000
   2021-10-31 17:00:04.197112704       20.680517         0.00000
...                                          ...             ...
   2021-11-03 04:04:55.558028928        0.000000         0.00000
   2021-11-03 04:04:56.558030592        0.000000         0.00000
   2021-11-03 04:04:57.558032256        0.000000         3.22539
   2021-11-03 04:04:58.558033920       20.680517         0.00000
   2021-11-03 04:04:59.558035712        0.000000         0.00000

                                            asun                  \
                                 Electron_Flux_0 Electron_Flux_1
   Time
20 2021-10-31 17:00:00.197105920       20.680517         6.45078
   2021-10-31 17:00:01.197107584        0.000000         0.00000
   2021-10-31 17:00:02.197109376       20.680517         0.00000
   2021-10-31 17:00:03.197111040       20.680517         3.22539
   2021-10-31 17:00:04.197112704        0.000000         0.00000
...                                          ...             ...
   2021-11-03 04:04:55.558028928        0.000000         0.00000
   2021-11-03 04:04:56.558030592        0.000000         0.00000
   2021-11-03 04:04:57.558032256        0.000000         0.00000
   2021-11-03 04:04:58.558033920        0.000000         0.00000
   2021-11-03 04:04:59.558035712        0.000000         0.00000

                                           north                  \
                                 Electron_Flux_0 Electron_Flux_1
   Time
20 2021-10-31 17:00:00.197105920        0.000000         0.00000
   2021-10-31 17:00:01.197107584       20.680517         0.00000
   2021-10-31 17:00:02.197109376        0.000000         0.00000
   2021-10-31 17:00:03.197111040        0.000000         0.00000
   2021-10-31 17:00:04.197112704        0.000000         3.22539
...                                          ...             ...
   2021-11-03 04:04:55.558028928        0.000000         0.00000
   2021-11-03 04:04:56.558030592        0.000000         0.00000
   2021-11-03 04:04:57.558032256        0.000000         0.00000
   2021-11-03 04:04:58.558033920        0.000000         0.00000
   2021-11-03 04:04:59.558035712        0.000000         0.00000

                                           south
                                 Electron_Flux_0 Electron_Flux_1
   Time
20 2021-10-31 17:00:00.197105920       20.680517         0.00000
   2021-10-31 17:00:01.197107584        0.000000         0.00000
   2021-10-31 17:00:02.197109376       20.680517         3.22539
   2021-10-31 17:00:03.197111040        0.000000         0.00000
   2021-10-31 17:00:04.197112704        0.000000         0.00000
...                                          ...             ...
   2021-11-03 04:04:55.558028928        0.000000         0.00000
   2021-11-03 04:04:56.558030592        0.000000         0.00000
   2021-11-03 04:04:57.558032256        0.000000         0.00000
   2021-11-03 04:04:58.558033920       20.680517         0.00000
   2021-11-03 04:04:59.558035712       20.680517         0.00000

[212700 rows x 8 columns]

## Data Reformation

In [10]:
resampled_data = {
                    particle: {
                        k: None
                        for k in resample_freqs
                    }
                    for particle in particles
                 }

If resampled data are already saved, skip the "resample" cell and run the "load resampled data" cell directly.

In [11]:
# resample
for particle in particles:
    for resample_freq in resample_freqs:
        if pexists(pjoin(dir_saves, f"resampled_data_{particle}_{int(resample_freq.total_seconds()/60)}min.pkl")):
            print("Skipping existing", particle, resample_freq)
            continue
        rp = []
        for i, df_event in particles_dfs[particle].groupby(level=0):
            rp.append(df_event.droplevel(0).loc[df_event_times.loc[i]["BG Start"]:df_event_times.loc[i]["End Time"]].resample(resample_freq, origin="start").mean())
        resampled_data[particle][resample_freq] = pd.concat({i: pe for i, pe in zip(particles_dfs[particle].index.levels[0], rp)}, axis="index")
        print("Saving", particle, resample_freq, f"resampled_data_{particle}_{int(resample_freq.total_seconds()/60)}min.pkl")
        resampled_data[particle][resample_freq].to_pickle(pjoin(dir_saves, f"resampled_data_{particle}_{int(resample_freq.total_seconds()/60)}min.pkl"))
        print("Done")

Saving protons 0:02:00 resampled_data_protons_2min.pkl
Done
Saving protons 0:05:00 resampled_data_protons_5min.pkl
Done
Saving protons 0:10:00 resampled_data_protons_10min.pkl
Done
Saving protons 0:30:00 resampled_data_protons_30min.pkl
Done
Saving electrons 0:02:00 resampled_data_electrons_2min.pkl
Done
Saving electrons 0:05:00 resampled_data_electrons_5min.pkl
Done
Saving electrons 0:10:00 resampled_data_electrons_10min.pkl
Done
Saving electrons 0:30:00 resampled_data_electrons_30min.pkl
Done

In [12]:
# load resampled data
for particle in particles:
    for resample_freq in resample_freqs:
        resampled_data[particle][resample_freq] = pd.read_pickle(pjoin(dir_saves, f"resampled_data_{particle}_{int(resample_freq.total_seconds()/60)}min.pkl"))

In [13]:
# group
def group_channels_de(df_to_group: pd.DataFrame, energy_bins_width: list[float], column_prefix: str = "", show_groups = True, group_size: int = 2) -> pd.DataFrame:
    channels = list(range(len(df_to_group.columns)))
    grouped_channels = [channels[c:c+group_size] for c in range(0, len(channels), group_size)]
    grouped_all = {}
    for group in grouped_channels:
        de = sum([energy_bins_width[group[i]] for i, _ in enumerate(group)])
        grouped_series = df_to_group.iloc[:, group[0]]*energy_bins_width[group[0]]
        for i, _ in enumerate(group[1:]):
            grouped_series = grouped_series.add(df_to_group.iloc[:, group[i]]*energy_bins_width[group[i]], fill_value=0)
        grouped_all[f"{column_prefix}{'_' if column_prefix != '' and show_groups else ''}{f'{group[0]}-{group[-1]}' if show_groups else ''}"] = grouped_series/de
    df_grouped = pd.DataFrame(grouped_all)
    return df_grouped

for particle in particles:
    for resample_freq in resample_freqs:
        grouped_dfs = {}
        for viewing in viewings:
            for mevlbl, proton_channels in group_options[particle].items():
                grouped_protons = []
                cname = f"{mevlbl} ({', '.join([str(c) for c in proton_channels])})"
                for _, df_event in resampled_data[particle][resample_freq].groupby(level=0):
                    grouped_protons.append(group_channels_de(
                        df_event.droplevel(0)[viewing][[f'{particle_prefix[particle]}_Flux_{channel}' for channel in proton_channels]],
                        energies[f'{particle_prefix[particle]}_Bins_Width'][proton_channels],
                        cname,
                        False,
                        len(proton_channels)
                    ))
                grouped_dfs[(viewing, cname)] = pd.concat({i: pe for i, pe in zip(resampled_data[particle][resample_freq].index.levels[0], grouped_protons)}, axis="index")
        resampled_data[particle][resample_freq] = pd.concat(grouped_dfs, axis="columns")

In [14]:
for particle in particles:
    print(particle)
    for resample_freq in resample_freqs:
        print(resample_freq)
        resampled_data[particle][resample_freq].columns = resampled_data[particle][resample_freq].columns.droplevel(2)
        display(resampled_data[particle][resample_freq])

protons
0:02:00

                                             sun                              \
                                 8 MeV (1, 2, 3) 25 MeV (18, 19) 50 MeV (27)
   Time
20 2021-10-31 19:00:03.209325312        0.837895        0.044890    0.021725
   2021-10-31 19:02:03.209325312        0.676820        0.104743    0.007242
   2021-10-31 19:04:03.209325312        0.695582        0.089780    0.007242
   2021-10-31 19:06:03.209325312        0.767850        0.074816    0.007242
   2021-10-31 19:08:03.209325312        0.999526        0.029927    0.000000
...                                          ...             ...         ...
   2021-11-03 01:56:03.209325312        2.426546        0.000000    0.000000
   2021-11-03 01:58:03.209325312        2.890453        0.014963    0.007242
   2021-11-03 02:00:03.209325312        3.140890        0.000000    0.000000
   2021-11-03 02:02:03.209325312        2.266027        0.029927    0.007242
   2021-11-03 02:04:03.209325312        2.355389        0.000000    0.000000

                                            asun                              \
                                 8 MeV (1, 2, 3) 25 MeV (18, 19) 50 MeV (27)
   Time
20 2021-10-31 19:00:03.209325312        0.820245        0.029927    0.007242
   2021-10-31 19:02:03.209325312        0.533395        0.029927    0.000000
   2021-10-31 19:04:03.209325312        0.731994        0.089780    0.000000
   2021-10-31 19:06:03.209325312        0.623870        0.089780    0.007242
   2021-10-31 19:08:03.209325312        0.766182        0.059853    0.000000
...                                          ...             ...         ...
   2021-11-03 01:56:03.209325312        1.462876        0.000000    0.000000
   2021-11-03 01:58:03.209325312        1.231201        0.014963    0.000000
   2021-11-03 02:00:03.209325312        1.336546        0.000000    0.000000
   2021-11-03 02:02:03.209325312        0.943796        0.014963    0.000000
   2021-11-03 02:04:03.209325312        1.430912        0.000000    0.000000

                                           north                              \
                                 8 MeV (1, 2, 3) 25 MeV (18, 19) 50 MeV (27)
   Time
20 2021-10-31 19:00:03.209325312        0.893069        0.014963    0.000000
   2021-10-31 19:02:03.209325312        0.784944        0.089780    0.007242
   2021-10-31 19:04:03.209325312        0.479889        0.014963    0.000000
   2021-10-31 19:06:03.209325312        0.678488        0.014963    0.000000
   2021-10-31 19:08:03.209325312        1.017732        0.014963    0.014483
...                                          ...             ...         ...
   2021-11-03 01:56:03.209325312        0.962002        0.000000    0.000000
   2021-11-03 01:58:03.209325312        1.161156        0.000000    0.000000
   2021-11-03 02:00:03.209325312        1.375182        0.000000    0.000000
   2021-11-03 02:02:03.209325312        1.320563        0.000000    0.000000
   2021-11-03 02:04:03.209325312        0.605664        0.000000    0.000000

                                           south
                                 8 MeV (1, 2, 3) 25 MeV (18, 19) 50 MeV (27)
   Time
20 2021-10-31 19:00:03.209325312        0.820801        0.074816    0.000000
   2021-10-31 19:02:03.209325312        0.820245        0.059853    0.007242
   2021-10-31 19:04:03.209325312        0.695026        0.044890    0.021725
   2021-10-31 19:06:03.209325312        0.696138        0.074816    0.014483
   2021-10-31 19:08:03.209325312        0.891957        0.000000    0.014483
...                                          ...             ...         ...
   2021-11-03 01:56:03.209325312        1.479971        0.014963    0.000000
   2021-11-03 01:58:03.209325312        1.446338        0.000000    0.000000
   2021-11-03 02:00:03.209325312        1.499844        0.014963    0.000000
   2021-11-03 02:02:03.209325312        1.517494        0.014963    0.000000
   2021-11-03 02:04:03.209325312        1.787250        0.000000    0.000000

[1653 rows x 12 columns]

0:05:00

                                             sun                              \
                                 8 MeV (1, 2, 3) 25 MeV (18, 19) 50 MeV (27)
   Time
20 2021-10-31 19:00:03.209325312        0.741361        0.071824    0.014483
   2021-10-31 19:05:03.209325312        0.849708        0.065838    0.002897
   2021-10-31 19:10:03.209325312        0.807348        0.077809    0.014483
   2021-10-31 19:15:03.209325312        0.713566        0.059853    0.008690
   2021-10-31 19:20:03.209325312        0.863606        0.053868    0.005793
...                                          ...             ...         ...
   2021-11-03 01:40:03.209325312        1.954245        0.017956    0.002897
   2021-11-03 01:45:03.209325312        2.099671        0.017956    0.000000
   2021-11-03 01:50:03.209325312        2.206016        0.017956    0.002897
   2021-11-03 01:55:03.209325312        2.826912        0.005985    0.002897
   2021-11-03 02:00:03.209325312        2.633845        0.011971    0.002897

                                            asun                              \
                                 8 MeV (1, 2, 3) 25 MeV (18, 19) 50 MeV (27)
   Time
20 2021-10-31 19:00:03.209325312        0.684436        0.047882    0.002897
   2021-10-31 19:05:03.209325312        0.705839        0.071824    0.002897
   2021-10-31 19:10:03.209325312        0.499318        0.065838    0.014483
   2021-10-31 19:15:03.209325312        0.862939        0.041897    0.005793
   2021-10-31 19:20:03.209325312        0.455624        0.089780    0.005793
...                                          ...             ...         ...
   2021-11-03 01:40:03.209325312        1.284596        0.005985    0.002897
   2021-11-03 01:45:03.209325312        1.571890        0.000000    0.000000
   2021-11-03 01:50:03.209325312        1.498844        0.000000    0.000000
   2021-11-03 01:55:03.209325312        1.412567        0.005985    0.000000
   2021-11-03 02:00:03.209325312        1.198319        0.005985    0.000000

                                           north                              \
                                 8 MeV (1, 2, 3) 25 MeV (18, 19) 50 MeV (27)
   Time
20 2021-10-31 19:00:03.209325312        0.799398        0.041897    0.002897
   2021-10-31 19:05:03.209325312        0.742251        0.017956    0.005793
   2021-10-31 19:10:03.209325312        0.649358        0.041897    0.008690
   2021-10-31 19:15:03.209325312        0.598604        0.071824    0.002897
   2021-10-31 19:20:03.209325312        0.491813        0.113721    0.014483
...                                          ...             ...         ...
   2021-11-03 01:40:03.209325312        1.377044        0.017956    0.005793
   2021-11-03 01:45:03.209325312        1.355864        0.000000    0.000000
   2021-11-03 01:50:03.209325312        1.449201        0.000000    0.002897
   2021-11-03 01:55:03.209325312        1.091973        0.005985    0.000000
   2021-11-03 02:00:03.209325312        1.199431        0.000000    0.000000

                                           south
                                 8 MeV (1, 2, 3) 25 MeV (18, 19) 50 MeV (27)
   Time
20 2021-10-31 19:00:03.209325312        0.784833        0.059853    0.005793
   2021-10-31 19:05:03.209325312        0.784833        0.041897    0.017380
   2021-10-31 19:10:03.209325312        0.749311        0.059853    0.011586
   2021-10-31 19:15:03.209325312        0.871110        0.047882    0.011586
   2021-10-31 19:20:03.209325312        0.656418        0.023941    0.014483
...                                          ...             ...         ...
   2021-11-03 01:40:03.209325312        1.619976        0.005985    0.000000
   2021-11-03 01:45:03.209325312        1.456483        0.000000    0.000000
   2021-11-03 01:50:03.209325312        1.449201        0.011971    0.002897
   2021-11-03 01:55:03.209325312        1.520469        0.011971    0.000000
   2021-11-03 02:00:03.209325312        1.564386        0.011971    0.000000

[661 rows x 12 columns]

0:10:00

                                             sun                              \
                                 8 MeV (1, 2, 3) 25 MeV (18, 19) 50 MeV (27)
   Time
20 2021-10-31 19:00:03.209325312        0.795535        0.068831    0.008690
   2021-10-31 19:10:03.209325312        0.760457        0.068831    0.011586
   2021-10-31 19:20:03.209325312        0.788363        0.041897    0.005793
   2021-10-31 19:30:03.209325312        0.694470        0.047882    0.004345
   2021-10-31 19:40:03.209325312        0.713455        0.044890    0.005793
...                                          ...             ...         ...
   2021-11-03 01:20:03.209325312        1.796061        0.000000    0.000000
   2021-11-03 01:30:03.209325312        2.138613        0.002993    0.001448
   2021-11-03 01:40:03.209325312        2.026958        0.017956    0.001448
   2021-11-03 01:50:03.209325312        2.516464        0.011971    0.002897
   2021-11-03 02:00:03.209325312        2.633845        0.011971    0.002897

                                            asun                              \
                                 8 MeV (1, 2, 3) 25 MeV (18, 19) 50 MeV (27)
   Time
20 2021-10-31 19:00:03.209325312        0.695137        0.059853    0.002897
   2021-10-31 19:10:03.209325312        0.681128        0.053868    0.010138
   2021-10-31 19:20:03.209325312        0.548850        0.077809    0.004345
   2021-10-31 19:30:03.209325312        0.688411        0.026934    0.007242
   2021-10-31 19:40:03.209325312        0.792338        0.053868    0.008690
...                                          ...             ...         ...
   2021-11-03 01:20:03.209325312        1.263305        0.002993    0.001448
   2021-11-03 01:30:03.209325312        1.435303        0.011971    0.001448
   2021-11-03 01:40:03.209325312        1.428243        0.002993    0.001448
   2021-11-03 01:50:03.209325312        1.455705        0.002993    0.000000
   2021-11-03 02:00:03.209325312        1.198319        0.005985    0.000000

                                           north                              \
                                 8 MeV (1, 2, 3) 25 MeV (18, 19) 50 MeV (27)
   Time
20 2021-10-31 19:00:03.209325312        0.770824        0.029927    0.004345
   2021-10-31 19:10:03.209325312        0.623981        0.056860    0.005793
   2021-10-31 19:20:03.209325312        0.638657        0.095765    0.010138
   2021-10-31 19:30:03.209325312        0.691941        0.056860    0.007242
   2021-10-31 19:40:03.209325312        0.659503        0.047882    0.007242
...                                          ...             ...         ...
   2021-11-03 01:20:03.209325312        1.323982        0.005985    0.000000
   2021-11-03 01:30:03.209325312        1.371318        0.002993    0.000000
   2021-11-03 01:40:03.209325312        1.366454        0.008978    0.002897
   2021-11-03 01:50:03.209325312        1.270587        0.002993    0.001448
   2021-11-03 02:00:03.209325312        1.199431        0.000000    0.000000

                                           south
                                 8 MeV (1, 2, 3) 25 MeV (18, 19) 50 MeV (27)
   Time
20 2021-10-31 19:00:03.209325312        0.784833        0.050875    0.011586
   2021-10-31 19:10:03.209325312        0.810211        0.053868    0.011586
   2021-10-31 19:20:03.209325312        0.795535        0.035912    0.010138
   2021-10-31 19:30:03.209325312        0.713788        0.062846    0.005793
   2021-10-31 19:40:03.209325312        0.710480        0.053868    0.008690
...                                          ...             ...         ...
   2021-11-03 01:20:03.209325312        1.551905        0.008978    0.000000
   2021-11-03 01:30:03.209325312        1.523999        0.002993    0.001448
   2021-11-03 01:40:03.209325312        1.538230        0.002993    0.000000
   2021-11-03 01:50:03.209325312        1.484835        0.011971    0.001448
   2021-11-03 02:00:03.209325312        1.564386        0.011971    0.000000

[331 rows x 12 columns]

0:30:00

                                             sun                              \
                                 8 MeV (1, 2, 3) 25 MeV (18, 19) 50 MeV (27)
   Time
20 2021-10-31 19:00:03.209325312        0.781452        0.059853    0.008690
   2021-10-31 19:30:03.209325312        0.694109        0.047882    0.006276
   2021-10-31 20:00:03.209325312        0.719190        0.058855    0.007242
   2021-10-31 20:30:03.209325312        0.680026        0.059853    0.002414
   2021-10-31 21:00:03.209325312        0.650387        0.039902    0.006759
...                                          ...             ...         ...
   2021-11-03 00:00:03.209325312        2.116951        0.009976    0.000966
   2021-11-03 00:30:03.209325312        2.065427        0.009976    0.001448
   2021-11-03 01:00:03.209325312        2.008650        0.008978    0.001931
   2021-11-03 01:30:03.209325312        2.227345        0.010973    0.001931
   2021-11-03 02:00:03.209325312        2.633845        0.011971    0.002897

                                            asun                              \
                                 8 MeV (1, 2, 3) 25 MeV (18, 19) 50 MeV (27)
   Time
20 2021-10-31 19:00:03.209325312        0.641705        0.063843    0.005793
   2021-10-31 19:30:03.209325312        0.730224        0.051873    0.008207
   2021-10-31 20:00:03.209325312        0.581695        0.045887    0.006759
   2021-10-31 20:30:03.209325312        0.695693        0.054865    0.005793
   2021-10-31 21:00:03.209325312        0.594379        0.045887    0.008690
...                                          ...             ...         ...
   2021-11-03 00:00:03.209325312        1.310159        0.008978    0.001448
   2021-11-03 00:30:03.209325312        1.282613        0.006983    0.000966
   2021-11-03 01:00:03.209325312        1.264778        0.004988    0.001448
   2021-11-03 01:30:03.209325312        1.439750        0.005985    0.000966
   2021-11-03 02:00:03.209325312        1.198319        0.005985    0.000000

                                           north                              \
                                 8 MeV (1, 2, 3) 25 MeV (18, 19) 50 MeV (27)
   Time
20 2021-10-31 19:00:03.209325312        0.677821        0.060851    0.006759
   2021-10-31 19:30:03.209325312        0.704884        0.057858    0.006759
   2021-10-31 20:00:03.209325312        0.684732        0.055863    0.005793
   2021-10-31 20:30:03.209325312        0.691830        0.051873    0.006276
   2021-10-31 21:00:03.209325312        0.588384        0.036909    0.005793
...                                          ...             ...         ...
   2021-11-03 00:00:03.209325312        1.417097        0.003990    0.000000
   2021-11-03 00:30:03.209325312        1.542677        0.007980    0.000966
   2021-11-03 01:00:03.209325312        1.296400        0.010973    0.000966
   2021-11-03 01:30:03.209325312        1.336120        0.004988    0.001448
   2021-11-03 02:00:03.209325312        1.199431        0.000000    0.000000

                                           south
                                 8 MeV (1, 2, 3) 25 MeV (18, 19) 50 MeV (27)
   Time
20 2021-10-31 19:00:03.209325312        0.796860        0.046885    0.011104
   2021-10-31 19:30:03.209325312        0.688967        0.052870    0.007724
   2021-10-31 20:00:03.209325312        0.656233        0.052870    0.008207
   2021-10-31 20:30:03.209325312        0.654324        0.044890    0.008207
   2021-10-31 21:00:03.209325312        0.639203        0.054865    0.002897
...                                          ...             ...         ...
   2021-11-03 00:00:03.209325312        1.425223        0.006983    0.001448
   2021-11-03 00:30:03.209325312        1.429966        0.007980    0.001448
   2021-11-03 01:00:03.209325312        1.496046        0.006983    0.000966
   2021-11-03 01:30:03.209325312        1.515688        0.005985    0.000966
   2021-11-03 02:00:03.209325312        1.564386        0.011971    0.000000

[111 rows x 12 columns]

electrons
0:02:00

                                          sun         asun        north  \
                                 1 MeV (0, 1) 1 MeV (0, 1) 1 MeV (0, 1)
   Time
20 2021-10-31 19:00:00.209323648     6.777853     5.735106     9.071896
   2021-10-31 19:02:00.209323648     7.716325     5.943655     8.863346
   2021-10-31 19:04:00.209323648     6.882128     5.318007     9.280444
   2021-10-31 19:06:00.209323648     5.839381     5.318007     8.550521
   2021-10-31 19:08:00.209323648     6.569304     5.630831     9.071896
...                                       ...          ...          ...
   2021-11-03 01:56:00.209323648     2.398317     1.668395     3.753888
   2021-11-03 01:58:00.209323648     2.085493     1.772669     4.066711
   2021-11-03 02:00:00.209323648     2.189768     1.772669     2.606867
   2021-11-03 02:02:00.209323648     2.502592     1.981218     3.128240
   2021-11-03 02:04:00.209323648     2.711141     0.625648     3.545338

                                        south
                                 1 MeV (0, 1)
   Time
20 2021-10-31 19:00:00.209323648     6.465029
   2021-10-31 19:02:00.209323648     8.654798
   2021-10-31 19:04:00.209323648     6.777853
   2021-10-31 19:06:00.209323648     7.820600
   2021-10-31 19:08:00.209323648     8.446247
...                                       ...
   2021-11-03 01:56:00.209323648     3.128240
   2021-11-03 01:58:00.209323648     3.753888
   2021-11-03 02:00:00.209323648     2.398317
   2021-11-03 02:02:00.209323648     3.441064
   2021-11-03 02:04:00.209323648     2.919691

[1653 rows x 4 columns]

0:05:00

                                          sun         asun        north  \
                                 1 MeV (0, 1) 1 MeV (0, 1) 1 MeV (0, 1)
   Time
20 2021-10-31 19:00:00.209323648     7.174097     5.505702     9.217880
   2021-10-31 19:05:00.209323648     6.339900     5.672541     8.717361
   2021-10-31 19:10:00.209323648     6.673579     6.548449     9.134459
   2021-10-31 19:15:00.209323648     6.381609     6.381609     9.551559
   2021-10-31 19:20:00.209323648     7.048966     6.214769     8.175133
...                                       ...          ...          ...
   2021-11-03 01:40:00.209323648     2.002074     2.168913     3.795597
   2021-11-03 01:45:00.209323648     2.877980     1.876944     2.961400
   2021-11-03 01:50:00.209323648     2.252333     1.668395     3.128240
   2021-11-03 01:55:00.209323648     2.752851     1.459845     3.712178
   2021-11-03 02:00:00.209323648     2.419172     1.626685     3.003110

                                        south
                                 1 MeV (0, 1)
   Time
20 2021-10-31 19:00:00.209323648     7.507776
   2021-10-31 19:05:00.209323648     7.758035
   2021-10-31 19:10:00.209323648     7.674615
   2021-10-31 19:15:00.209323648     9.092750
   2021-10-31 19:20:00.209323648     8.008294
...                                       ...
   2021-11-03 01:40:00.209323648     2.377462
   2021-11-03 01:45:00.209323648     3.044820
   2021-11-03 01:50:00.209323648     2.836271
   2021-11-03 01:55:00.209323648     3.420209
   2021-11-03 02:00:00.209323648     2.919691

[661 rows x 4 columns]

0:10:00

                                          sun         asun        north  \
                                 1 MeV (0, 1) 1 MeV (0, 1) 1 MeV (0, 1)
   Time
20 2021-10-31 19:00:00.209323648     6.756998     5.589121     8.967621
   2021-10-31 19:10:00.209323648     6.527594     6.465028     9.343009
   2021-10-31 19:20:00.209323648     6.006220     5.901946     8.800782
   2021-10-31 19:30:00.209323648     7.090677     6.444174     9.238734
   2021-10-31 19:40:00.209323648     6.319045     5.985366     9.926948
...                                       ...          ...          ...
   2021-11-03 01:20:00.209323648     1.960364     1.897799     3.545338
   2021-11-03 01:30:00.209323648     2.460882     2.127203     2.669431
   2021-11-03 01:40:00.209323648     2.440027     2.022928     3.378499
   2021-11-03 01:50:00.209323648     2.502592     1.564120     3.420209
   2021-11-03 02:00:00.209323648     2.419172     1.626685     3.003110

                                        south
                                 1 MeV (0, 1)
   Time
20 2021-10-31 19:00:00.209323648     7.632905
   2021-10-31 19:10:00.209323648     8.383683
   2021-10-31 19:20:00.209323648     7.695470
   2021-10-31 19:30:00.209323648     7.007257
   2021-10-31 19:40:00.209323648     7.549485
...                                       ...
   2021-11-03 01:20:00.209323648     2.252333
   2021-11-03 01:30:00.209323648     2.815416
   2021-11-03 01:40:00.209323648     2.711141
   2021-11-03 01:50:00.209323648     3.128240
   2021-11-03 02:00:00.209323648     2.919691

[331 rows x 4 columns]

0:30:00

                                          sun         asun        north  \
                                 1 MeV (0, 1) 1 MeV (0, 1) 1 MeV (0, 1)
   Time
20 2021-10-31 19:00:00.209323648     6.430271     5.985366     9.037136
   2021-10-31 19:30:00.209323648     6.729191     6.138301     9.787914
   2021-10-31 20:00:00.209323648     6.249528     5.943655     9.120557
   2021-10-31 20:30:00.209323648     6.124398     5.985366     9.363864
   2021-10-31 21:00:00.209323648     6.353803     5.561315     9.148363
...                                       ...          ...          ...
   2021-11-03 00:00:00.209323648     2.460882     2.210623     3.403135
   2021-11-03 00:30:00.209323648     2.391366     2.266236     3.357644
   2021-11-03 01:00:00.209323648     2.314898     2.148058     3.378499
   2021-11-03 01:30:00.209323648     2.467834     1.904750     3.156047
   2021-11-03 02:00:00.209323648     2.419172     1.626685     3.003110

                                        south
                                 1 MeV (0, 1)
   Time
20 2021-10-31 19:00:00.209323648     7.904019
   2021-10-31 19:30:00.209323648     7.605099
   2021-10-31 20:00:00.209323648     7.507776
   2021-10-31 20:30:00.209323648     7.612050
   2021-10-31 21:00:00.209323648     7.340936
...                                       ...
   2021-11-03 00:00:00.209323648     2.818547
   2021-11-03 00:30:00.209323648     2.738948
   2021-11-03 01:00:00.209323648     2.328801
   2021-11-03 01:30:00.209323648     2.884932
   2021-11-03 02:00:00.209323648     2.919691

[111 rows x 4 columns]

## Calculations

### Onset

In [15]:
def _onset_detection_sigma(
    series: pd.Series,
    s: int = 3,
    n: int = 3,
    bg_start: int | datetime = 0,
    bg_end: int | datetime = 12
) -> tuple:
    """Returns:

    1. Onset time or None if no event detected
    2. Background start
    3. Background end
    4. Background Level
    5. Threshold
    """
    if type(bg_start) is int:
        bg_start = series.index[bg_start]
    if type(bg_end) is int:
        bg_end = series.index[bg_end]
    bg_level = (bg_series := series[bg_start:bg_end]).mean()
    threshold = bg_level + s * bg_series.std()
    onset_time = None
    data_series = series[bg_end:]

    streak = 0
    for index, value in data_series.items():
        if value > threshold:
            streak += 1
            if onset_time is None:
                onset_time = index
        else:
            streak = 0
            onset_time = None

        if streak >= n:
            break

    if streak < n:
        onset_time = None
    
    if onset_time is not None:
        onset_value = data_series.loc[onset_time]
        for index, value in data_series.loc[:onset_time - timedelta(milliseconds=1)].iloc[::-1].items():
            if value < onset_value:
                onset_time = index
                onset_value = value
            else:
                break
            
    return (
        onset_time,
        bg_start,
        bg_end,
        {"bg_level": bg_level, "threshold": threshold},
    )

In [16]:
df_events = pd.DataFrame([])
for particle in particles:
    df_tpart = pd.DataFrame([])
    for resample_freq in resample_freqs:
        df_tresample = pd.DataFrame([])
        for viewing in viewings:
            df_tview = pd.DataFrame([])
            for mevlbl, particle_channels in group_options[particle].items():
                cname = f"{mevlbl} ({', '.join([str(c) for c in particle_channels])})"
                df_tmev = pd.concat([pd.DataFrame({"Onset Time": [],
                                                   "BG Start": [],
                                                   "BG End": [],
                                                   "BG mean": [],
                                                   "Threshold": []})],
                                    axis="columns",
                                    keys=[cname])
                for i, df_event in resampled_data[particle][resample_freq].groupby(level=0):
                    onset = _onset_detection_sigma(df_event.droplevel(0).loc[:min(df_event_times.loc[i, "BG End"]+timedelta(hours=6),
                                                                                  df_event_times.loc[i, "End Time"]), (viewing, cname)],
                                                   s=2,
                                                   bg_start=df_event_times.loc[i, "BG Start"],
                                                   bg_end=df_event_times.loc[i, "BG End"])
                    df_tmev.loc[i] = [onset[0], onset[1], onset[2], onset[3]["bg_level"], onset[3]["threshold"]]
                df_tview = pd.concat([df_tview, df_tmev], axis="columns")
            df_tview = pd.concat([df_tview], axis="columns", keys=[viewing])
            df_tresample = pd.concat([df_tresample, df_tview], axis="columns")
        df_tresample = pd.concat([df_tresample], axis="columns", keys=[f"{int(resample_freq.total_seconds()/60)} mins"])
        df_tpart = pd.concat([df_tpart, df_tresample], axis="columns")
    df_tpart = pd.concat([df_tpart], axis="columns", keys=[particle])
    df_events = pd.concat([df_events, df_tpart], axis="columns")
df_events = df_events.sort_index(axis="index", level=list(range(df_events.index.nlevels)))
display(df_events)

                         protons                                          \
                          2 mins
                             sun
                 8 MeV (1, 2, 3)
                      Onset Time            BG Start              BG End
20 2021-11-01 02:52:03.209325312 2021-10-31 19:00:00 2021-11-01 01:30:00

                                                                          \


                                     25 MeV (18, 19)
     BG mean Threshold                    Onset Time            BG Start
20  0.512091  0.953951 2021-11-01 02:46:03.209325312 2021-10-31 19:00:00

                                            ...                     electrons  \
                                            ...                       30 mins
                                            ...                         north
                                            ...                  1 MeV (0, 1)
                BG End   BG mean Threshold  ...                    Onset Time
20 2021-11-01 01:30:00  0.039749  0.093677  ... 2021-11-01 01:30:00.209323648

                                                                 \



              BG Start              BG End   BG mean  Threshold
20 2021-10-31 19:00:00 2021-11-01 01:30:00  7.955355  10.739344

                                                                          \

                           south
                    1 MeV (0, 1)
                      Onset Time            BG Start              BG End
20 2021-11-01 01:30:00.209323648 2021-10-31 19:00:00 2021-11-01 01:30:00





     BG mean Threshold
20  6.604062  8.821176

[1 rows x 320 columns]

### Peak Flux

In [17]:
for particle in particles:
    to_df = {}
    for resample_freq in resample_freqs:
        resample_lbl = f"{int(resample_freq.total_seconds()/60)} mins"
        for viewing in viewings:
            for mevlbl, energy_channels in group_options[particle].items():
                cname = f"{mevlbl} ({', '.join([str(c) for c in energy_channels])})"
                df_events[(particle, resample_lbl, viewing, cname, "Peak Time")] = [v.idxmax()
                                                                                    if not pd.isna(onset_time := df_events.loc[i][particle][resample_lbl][viewing][cname]["Onset Time"]) \
                                                                                    and not (v := resampled_data[particle][resample_freq].loc[i].loc[onset_time:min(onset_time + timedelta(hours=18),
                                                                                                                                                                    df_event_times.loc[i]["End Time"])][viewing][cname]).empty
                                                                                    else np.nan
                                                                                    for i in resampled_data[particle][resample_freq].index.levels[0]]
                df_events[(particle, resample_lbl, viewing, cname, "Peak Flux")] = [resampled_data[particle][resample_freq].loc[i].loc[peak_time][viewing][cname]
                                                                                    if not pd.isna(peak_time := row[particle][resample_lbl][viewing][cname]["Peak Time"])
                                                                                    else np.nan
                                                                                    for i, row in df_events.iterrows()]
df_events

                         protons                                          \
                          2 mins
                             sun
                 8 MeV (1, 2, 3)
                      Onset Time            BG Start              BG End
20 2021-11-01 02:52:03.209325312 2021-10-31 19:00:00 2021-11-01 01:30:00

                                                                          \


                                     25 MeV (18, 19)
     BG mean Threshold                    Onset Time            BG Start
20  0.512091  0.953951 2021-11-01 02:46:03.209325312 2021-10-31 19:00:00

                                            ...                     electrons  \
                                            ...                       10 mins
                                            ...                         south
                                            ...                  1 MeV (0, 1)
                BG End   BG mean Threshold  ...                     Peak Time
20 2021-11-01 01:30:00  0.039749  0.093677  ... 2021-11-01 03:00:00.209323648

                                                        \
                                     30 mins
                                         sun
                                1 MeV (0, 1)
     Peak Flux                     Peak Time Peak Flux
20  100.020256 2021-11-01 03:00:00.209323648  97.96257

                                                                          \

                            asun                                   north
                    1 MeV (0, 1)                            1 MeV (0, 1)
                       Peak Time Peak Flux                     Peak Time
20 2021-11-01 03:30:00.209323648  52.19294 2021-11-01 03:30:00.209323648



                                      south
                               1 MeV (0, 1)
    Peak Flux                     Peak Time Peak Flux
20  99.352905 2021-11-01 03:00:00.209323648  83.88549

[1 rows x 448 columns]

### Fluence

In [18]:
for particle in particles:
    for resample_freq in resample_freqs:
        resample_lbl = f"{int(resample_freq.total_seconds()/60)} mins"
        for viewing in viewings:
            for mevlbl, energy_channels in group_options[particle].items():
                cname = f"{mevlbl} ({', '.join([str(c) for c in energy_channels])})"
                starts = []
                ends = []
                fluences_fs_fe = []
                for i in df_events.index:
                    try:
                        timeseries = resampled_data[particle][resample_freq].loc[i][viewing][cname]
                    except KeyError:
                        starts.append(None)
                        ends.append(None)
                        fluences_fs_fe.append(None)
                        continue
                    peak_time = df_events.loc[i][particle][resample_lbl][viewing][cname]["Peak Time"]
                    onset_time = df_events.loc[i][particle][resample_lbl][viewing][cname]["Onset Time"]
                    if not pd.isna(peak_time):
                        timeseries = timeseries.loc[onset_time:df_event_times.loc[i]["End Time"]]
                        threshold = df_events.loc[i][particle][resample_lbl][viewing][cname]["Peak Flux"] / 2
                        fluence_start = None
                        needed_points = 2
                        while fluence_start is None and needed_points > 0:
                            n = 0
                            for j in range(len(timeseries[:peak_time]) - 1, -1, -1):
                                v = timeseries.iloc[j]
                                if v <= threshold:
                                    n += 1
                                    if n == needed_points:
                                        fluence_start = timeseries.index[j + (needed_points - 1)]
                                        break
                                else:
                                    n = 0
                            needed_points -= 1
                        if fluence_start is None or fluence_start < onset_time:
                            fluence_start = onset_time
                        fluence_end = None
                        needed_points = 2
                        while fluence_end is None and needed_points > 0:
                            n = 0
                            for j, v in enumerate(timeseries.loc[peak_time:], start=list(timeseries.index).index(peak_time)):
                                if v <= threshold:
                                    n += 1
                                    if n == needed_points:
                                        fluence_end = timeseries.index[j - (needed_points - 1)]
                                        break
                                else:
                                    n = 0
                            needed_points -= 1
                        if fluence_end is None or fluence_end > timeseries.index[-1]:
                            fluence_end = timeseries.index[-1]
                    
                        starts.append(fluence_start)
                        ends.append(fluence_end)
                        fluences_fs_fe.append(np.trapezoid(resampled_data[particle][resample_freq].loc[i, (viewing, cname)].loc[fluence_start:fluence_end], dx=resample_freq.seconds))
                    else:
                        starts.append(None)
                        ends.append(None)
                        fluences_fs_fe.append(None)
                df_events.loc[slice(None), (particle, resample_lbl, viewing, cname, "Fluence Start")] = starts
                df_events.loc[slice(None), (particle, resample_lbl, viewing, cname, "Fluence End")] = ends
                df_events.loc[slice(None), (particle, resample_lbl, viewing, cname, "Fluence")] = fluences_fs_fe
df_events = df_events[df_events.columns.sortlevel(3)[0].values]
df_events

                       electrons                                          \
                         10 mins
                            asun
                    1 MeV (0, 1)
                      Onset Time            BG Start              BG End
20 2021-11-01 01:30:00.209323648 2021-10-31 19:00:00 2021-11-01 01:30:00

                                                                 \



     BG mean Threshold                     Peak Time  Peak Flux
20  5.185926   6.84853 2021-11-01 03:30:00.209323648  58.936039

                                                                              \



                   Fluence Start                   Fluence End       Fluence
20 2021-11-01 02:20:00.209323648 2021-11-01 05:20:00.209323648  441357.09375

    ...                       protons                                          \
    ...                        5 mins
    ...                           sun
    ...               8 MeV (1, 2, 3)
    ...                    Onset Time            BG Start              BG End
20  ... 2021-11-01 02:45:03.209325312 2021-10-31 19:00:00 2021-11-01 01:30:00

                                                                \



    BG mean Threshold                     Peak Time  Peak Flux
20  0.51209   0.91525 2021-11-01 04:10:03.209325312  27.679691





                   Fluence Start                   Fluence End        Fluence
20 2021-11-01 03:45:03.209325312 2021-11-01 07:10:03.209325312  239227.546875

[1 rows x 640 columns]

## Plot

### Timeseries

In [19]:
tolerance = 0.1 # allowed transitions from valid to zero or NaN values after onset time as a percentage of the total points
adjustable_tolerance = False # if True, tolerance is adjusted based on resampling frequency (higher freq = higher tolerance)

for event_no in df_events.index:
    # Choose what to plot
    fastest_viewings = {}
    best_resamples = {}
    ratios = {}
    lengths = {}
    zeroes = {}
    for particle in particles:
        fastest_viewings[particle] = {}
        best_resamples[particle] = {}
        ratios[particle] = {}
        lengths[particle] = {}
        zeroes[particle] = {}
        for mev in group_options[particle].keys():
            mevlbl = f"{mev} ({', '.join([str(c) for c in group_options[particle][mev]])})"
            fastest_viewings[particle][mevlbl] = {}
            ratios[particle][mevlbl] = {}
            lengths[particle][mevlbl] = {}
            zeroes[particle][mevlbl] = {}
            # identify the fastest onset among all viewings for each resampling frequency
            for resample_freq in resample_freqs:
                resample_lbl = f"{int(resample_freq.total_seconds()/60)} mins"
                temp = [i if not pd.isna(i := df_events.loc[event_no][particle][resample_lbl][viewing][mevlbl]["Onset Time"]) else datetime.utcnow() + timedelta(days=1) for viewing in viewings]
                fastest_onset = min(temp)
                fastest_viewing = viewings[(temp).index(fastest_onset)]
                if fastest_onset > datetime.utcnow():
                    fastest_viewings[particle][mevlbl][resample_lbl] = None
                    continue
                fastest_viewings[particle][mevlbl][resample_lbl] = fastest_viewing
            
            # identify the best resolution
            best_resample = None
            for resample_freq in resample_freqs:
                resample_lbl = f"{int(resample_freq.total_seconds()/60)} mins"
                if pd.isna(fastest_viewings[particle][mevlbl][resample_lbl]):
                    continue
                ot = df_events.loc[event_no][particle][resample_lbl][fastest_viewings[particle][mevlbl][resample_lbl]][mevlbl]["Onset Time"]
                ts = resampled_data[particle][resample_freq].loc[event_no][fastest_viewings[particle][mevlbl][resample_lbl]][mevlbl].loc[ot:]
                n_zeroes = len(ts[(ts == 0) | pd.isna(ts)])
                n_changes = 0
                during_streak = False
                for v in ts:
                    if v == 0 or pd.isna(v):
                        if not during_streak:
                            during_streak = True
                            n_changes += 1
                    else:
                        during_streak = False
                ratio = n_changes / len(ts)
                rate_adjustment_multiplier = 1 + resample_freq.total_seconds() / timedelta(minutes=60).total_seconds()
                ratios[particle][mevlbl][resample_lbl] = ratio
                lengths[particle][mevlbl][resample_lbl] = len(ts)
                zeroes[particle][mevlbl][resample_lbl] = n_zeroes
                if ratio < tolerance * (rate_adjustment_multiplier if adjustable_tolerance else 1) \
                and n_zeroes < len(ts) - n_zeroes:
                    best_resample = resample_freq
                    break
            best_resamples[particle][mevlbl] = best_resample
    
    # plot
    fig, axs = plt.subplots(figsize=(15, 10),
                            nrows=len([True for k in group_options.keys() for _ in group_options[k]]),
                            ncols=1,
                            sharex=True)
    time_formatter = mdates.DateFormatter("%H:%M")
    i_ax = 0
    for particle, mevs in reversed(group_options.items()):
        for mev in mevs:
            # ax parameters
            ax_title_params = {
                "y": 0.85,
                "loc": "right",
                "fontdict": {"fontweight": "bold"},
                "color": "black"
            }
            axs[i_ax].grid()
            axs[i_ax].set_yscale("log")
            mevlbl = f"{mev} ({', '.join([str(c) for c in group_options[particle][mev]])})"
            best_resample = best_resamples[particle][mevlbl]
            if pd.isna(best_resample):
                all_nones = True
                ax_title_params["color"] = "red"
                for resample_freq in reversed(resample_freqs):
                    resample_lbl = f"{int(resample_freq.total_seconds()/60)} mins"
                    if not pd.isna(fastest_viewings[particle][mevlbl][resample_lbl]):
                        all_nones = False
                        best_resample = resample_freq
                        break
                if all_nones:
                    axs[i_ax].set_title(f"{mevlbl.split('(')[0].strip()} {particle}", **ax_title_params)
                    axs[i_ax].text(df_event_times.loc[event_no]["BG Start"] + abs(df_event_times.loc[event_no]["End Time"] - df_event_times.loc[event_no]["BG Start"])/2,
                                   5,
                                   "No event detected",
                                   color="black",
                                   horizontalalignment="center")
                    i_ax += 1
                    continue
            best_resample_lbl = f"{int(best_resample.total_seconds()/60)} mins"
            best_viewing = fastest_viewings[particle][mevlbl][best_resample_lbl]
            axs[i_ax].set_title(f"{mevlbl.split('(')[0].strip()} {particle} ({best_viewing} viewing, {best_resample_lbl} resolution)", **ax_title_params)
            top_lim = 1e6
            
            # set variables
            ratio = ratios[particle][mevlbl][best_resample_lbl]
            length = lengths[particle][mevlbl][best_resample_lbl]
            n_zeroes = zeroes[particle][mevlbl][best_resample_lbl]
            flux = resampled_data[particle][best_resample].loc[event_no][best_viewing][mevlbl]
            bg_start = df_events.loc[event_no][particle][best_resample_lbl][best_viewing][mevlbl]["BG Start"]
            bg_end = df_events.loc[event_no][particle][best_resample_lbl][best_viewing][mevlbl]["BG End"]
            bg_level = df_events.loc[event_no][particle][best_resample_lbl][best_viewing][mevlbl]["BG mean"]
            peak_time = df_events.loc[event_no][particle][best_resample_lbl][best_viewing][mevlbl]["Peak Time"]
            peak_flux = df_events.loc[event_no][particle][best_resample_lbl][best_viewing][mevlbl]["Peak Flux"]
            if not pd.isna(peak_time):
                top_lim = float(f"1e{int(f'{peak_flux:e}'.split('e')[1]) + 2}")
            bot_lim = float(f"1e{int(f'{bg_level:e}'.split('e')[1]) - 1}") if not pd.isna(bg_level) and bg_level > 0 else float(f"1e{int(f'{top_lim:e}'.split('e')[1]) - 4}")
            threshold = df_events.loc[event_no][particle][best_resample_lbl][best_viewing][mevlbl]["Threshold"]
            onset_time = df_events.loc[event_no][particle][best_resample_lbl][best_viewing][mevlbl]["Onset Time"]
            fluence_start = df_events.loc[event_no][particle][best_resample_lbl][best_viewing][mevlbl]["Fluence Start"]
            fluence_end = df_events.loc[event_no][particle][best_resample_lbl][best_viewing][mevlbl]["Fluence End"]
            fluence = df_events.loc[event_no][particle][best_resample_lbl][best_viewing][mevlbl]["Fluence"]

            # data plot
            axs[i_ax].plot(flux.index, flux.values, label="flux", color="orange")
            axs[i_ax].fill_between([bg_start, bg_end], bot_lim, top_lim, color="green", alpha=0.3, label="background sample")
            axs[i_ax].axhline(y=bg_level, color="blue", linestyle="--", label="background level")
            if not pd.isna(peak_time):
                axs[i_ax].scatter(peak_time, peak_flux, color="red", zorder=5, label=f"peak flux ({peak_flux:.2E}/{peak_time.strftime('%Y-%m-%d %H:%M')})")
                axs[i_ax].axhline(y=peak_flux/2, color="purple", linestyle="--", label="half peak flux")
            axs[i_ax].axhline(y=threshold, color="red", linestyle="--", label="2\u03C3 threshold")
            if not pd.isna(onset_time):
                axs[i_ax].axvline(x=onset_time, color="green", linestyle="--", label=f"onset time ({onset_time.strftime('%Y-%m-%d %H:%M')})")
            if not pd.isna(fluence_start) and not pd.isna(fluence_end):
                axs[i_ax].fill_between([fluence_start, fluence_end], bot_lim, top_lim, color="brown", alpha=0.2, label=f"fluence ({fluence:.2E})")
            shocktimes_in_plot = []
            for shocktime in shocktimes:
                if flux.index[0] <= shocktime <= flux.index[-1]:
                    shocktimes_in_plot.append(shocktime)
                    axs[i_ax].axvline(x=shocktime, color="purple", linestyle=":", label=f"shock time ({shocktime.strftime('%Y-%m-%d %H:%M')})")
                    continue
                if shocktime > flux.index[-1]:
                    break

            # text labels
            axs[i_ax].text(peak_time + timedelta(minutes=15),
                           peak_flux,
                           f"{peak_flux:.2E}/{peak_time.strftime('%Y-%m-%d %H:%M')}",
                           color="red")
            axs[i_ax].text(onset_time + timedelta(minutes=15),
                           bot_lim * 10,
                           f"{onset_time.strftime('%Y-%m-%d %H:%M')}",
                           color="green")
            axs[i_ax].text(fluence_start + abs(fluence_end - fluence_start)/2,
                           top_lim / 5,
                           f"{fluence:.2E}",
                           color="brown",
                           horizontalalignment="center")
            axs[i_ax].text(flux.index[-1],
                           bot_lim * 2,
                           f"ratio={ratio:.2f}, #zeroes={n_zeroes}, #non-zeroes={length-n_zeroes}",
                           horizontalalignment="right",
                           verticalalignment="bottom")
            if len(shocktimes_in_plot) > 0:
                for shocktime in shocktimes_in_plot:
                    axs[i_ax].text(shocktime + timedelta(minutes=15),
                                   bot_lim * 10,
                                   f"{shocktime.strftime('%Y-%m-%d %H:%M')}",
                                   color="purple")
            
            # extra ax parameters
            axs[i_ax].set_ylim([bot_lim, top_lim])
            axs[i_ax].set_xlim([flux.index[0], flux.index[-1]])

            i_ax += 1
    # fig parameters
    fig.suptitle(f"Event {event_no}", y=1.0005)
    fig.supylabel(r"Flux (particle/(cm$^2$ s sr MeV))")
    fig.supxlabel("Time (UTC)")
    axs[-1].xaxis.set_major_formatter(time_formatter)
    hl = [
        ("Data", Line2D([0], [0], color="orange")),
        ("BG sample", Patch(facecolor="green", alpha=0.3)),
        ("BG Level", Line2D([0], [0], color="blue", linestyle="--")),
        ("Peak Flux", Line2D([0], [0], marker="o", color="white", markerfacecolor="red")),
        ("Half Peak Flux", Line2D([0], [0], color="purple", linestyle="--")),
        ("3\u03C3 Threshold", Line2D([0], [0], color="red", linestyle="--")),
        ("Onset Time", Line2D([0], [0], color="green", linestyle="--")),
        ("Fluence", Patch(facecolor="brown", alpha=0.2)),
        ("Shock Time", Line2D([0], [0], color="purple", linestyle=":")),
    ]
    labels = [item[0] for item in hl]
    handles = [item[1] for item in hl]
    fig.legend(handles, labels, bbox_to_anchor=(0.5, 0.985), loc='upper center', ncol=9)
    fig.tight_layout()

    # plt.show()
    plt.savefig(pjoin(dir_plots, f"event_{event_no:03}.png"))
    plt.close()